name: Build and test on push
on:
  push:
    branches:
      - main
env:
  SCHOOLID: ${{ secrets.TEST_SCHOOLID }}
  USERNAME: ${{ secrets.TEST_USERNAME }}
  PASSWORD: ${{ secrets.TEST_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run the test
        run: |
          npm run test -- "$SCHOOLID" "$USERNAME" "$PASSWORD"
