name: Build and test on push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Run the test
        run: |
          yarn test "$secrets.SCHOOLID" "$secrets.USERNAME" "$secrets.PASSWORD"
